### ISSUE TITLE
Versions 10.11 and 10.12 don't build with GHC 9.4.8

### ISSUE THREAD

**Issue by eddywestbrook** [LeventErkok/sbv#726]
When I try to build either `sbv-10.11` or `sbv-10.12` under GHC 9.4.8, I get the following error:

```
Data/SBV/Core/Model.hs:64:1: error: [-Wdodgy-imports, -Werror=dodgy-imports]
    Module ‘GHC.TypeLits’ does not export ‘SChar’
   |
64 | import GHC.TypeLits hiding (SChar)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I'm assuming it's because `SChar` was only added to the `GHC.TypeLits` package starting with base version 4.18, while GHC 9.4.8 uses base version 4.17. FWIW, `ghcup` (at least for me) still recommends using GHC 9.4.8, which is why I'm using it.

**Comment by LeventErkok** [comment]
I’d hate people to have a version that had a bug that’s already been fixed. 

There’s a couple of other places where we do the CPP trick. I think this one is similar. I’ll release a version with this patched in a couple of weeks.

**Comment by eddywestbrook** [comment]
Cool, thanks Levent!

**Comment by LeventErkok** [comment]
@eddywestbrook I put in a band-aid for compiling against older versions. Can you give it a try and let me know if it solves the problem?

**Comment by eddywestbrook** [comment]
@LeventErkok It looks like you're using the `TypeAbstractions` feature in `Data/SBV/Tools/KnuckleDragger.hs`, which it seems wasn't added until GHC 9.8.1. So unless you're going to remove the use of type abstractions in that tool or conditionally remove it from SBV for older versions of GHC, it's not going to work with those older versions.

**Comment by LeventErkok** [comment]
Good catch; I bumped base to be at least 4.19

**Comment by LeventErkok** [comment]
I believe we've resolved all the issues here. Closing the ticket. Feel free to open another one if otherwise.
