### ISSUE TITLE
sbv-11.5 fails to build with GHC 9.6 (and below)

### ISSUE THREAD

**Issue by andreasabel** [LeventErkok/sbv#739]
https://hackage.haskell.org/package/sbv-11.5/reports/1:
```
Data/SBV/SMT/SMTLib2.hs:82:34: error: [GHC-88464]
    Variable not in scope:
      foldl'
        :: (Set Op -> (a0, SBVExpr) -> Set Op)
           -> Set a1 -> Data.Sequence.Internal.Seq (SV, SBVExpr) -> Set a
    Suggested fixes:
      " Perhaps use one of these:
          BC.foldl' (imported from Data.ByteString.Char8),
          IM.foldl' (imported from Data.IntMap.Strict),
          Set.foldl' (imported from Data.Set)
      " Add foldl' to one of these import lists:
          Data.List (at Data/SBV/SMT/SMTLib2.hs:25:1-58)
          Data.Set (at Data/SBV/SMT/SMTLib2.hs:31:1-43)
   |
82 |         allTopOps = Set.toList $ foldl' (\sofar (_, SBVApp o _) -> Set.insert o sofar) Set.empty asgnsSeq
   |                                  ^^^^^^
```
If it is supposed to build only with GHC 9.8 and up (like `master`), the lower bound of `base` should be revised.

**Comment by LeventErkok** [comment]
Already fixed in https://github.com/LeventErkok/sbv/commit/9f5fb9f059368386de45944f506cae6d7584b235

I'll make a new release in about a week or so. Thanks.

**Comment by andreasabel** [comment]
> Already fixed in [9f5fb9f](https://github.com/LeventErkok/sbv/commit/9f5fb9f059368386de45944f506cae6d7584b235)

Is the Changelog for 11.5.5 correct? Typo?

**Comment by LeventErkok** [comment]
9.8.4 is correct. 

I need to figure out what the base version is and update the constraint. Do you know what it is for 9.8.4?

**Comment by andreasabel** [comment]
This is a good reference: https://www.snoyman.com/base/

> 9.8.4 is correct.

Ah, I was surprised, because 9.8 isn't even the recommended GHC version yet (just lately switched from 9.4 to 9.6).

**Comment by LeventErkok** [comment]
SBV 11.16 is now on hackage, and it compiles cleanly with GHC 9.8.4.
