### ISSUE TITLE
sbv-5.11 doesn't compile with GHC 8.0.1

### ISSUE THREAD

**Issue by peti** [LeventErkok/sbv#222]
Citing from http://hydra.cryp.to/build/1810495/nixlog/2/raw:

~~~
Building sbv-5.11...
Preprocessing library sbv-5.11...
[ 1 of 83] Compiling Data.SBV.Utils.TDiff ( Data/SBV/Utils/TDiff.hs, dist/build/Data/SBV/Utils/TDiff.o )
[ 2 of 83] Compiling GHC.SrcLoc.Compat ( GHC/SrcLoc/Compat.hs, dist/build/GHC/SrcLoc/Compat.o )

GHC/SrcLoc/Compat.hs:9:1: error:
    Failed to load interface for ‘GHC.SrcLoc’
    Use -v to see a list of the files searched for.
~~~~

**Comment by LeventErkok** [comment]
@peti Thanks. We're aware of this and are working on it.

@acfoltzer Any progress? (not that it's hugely urgent.)

**Comment by LeventErkok** [comment]
@acfoltzer Adam: I pushed in some changes over the weekend, and looks like we got both 7.10/8.0 supported now. I'm intending to do a hackage release later today. If you can do a quick compile of Cryptol to make sure all is well from HEAD, that'd be awesome.

**Comment by acfoltzer** [comment]
All looks green for Cryptol and SAW, thanks! 👍

**Comment by LeventErkok** [comment]
@acfoltzer Thanks!

@peti SBV 5.12 is now up on hackage, which builds on GHC 8.0.1. Thanks for the report!
